site_name: waterrocketpy
site_description: A modular Python package for simulating water rockets.
site_author: Cube002
site_url: https://Cube002.github.io/waterrocketpy
repo_url: https://github.com/Cube002/waterrocketpy

copyright: "Copyright &copy; 2024 - 2024 Pablo M"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings:
        handlers:
        python:
            paths: ["."]
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]

markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/Cube002/waterrocketpy/issues
    - Examples:
        - examples/intro.ipynb
    - API Reference:
        - Common: api/common.md
        - Main: api/main.md
        - Analysis / Energy_Breakdown: api/analysis/energy_breakdown.md
        - Analysis / Energy_Breakdown_Plot: api/analysis/energy_breakdown_plot.md
        - Core / Constants: api/core/constants.md
        - Core / Physics_Engine: api/core/physics_engine.md
        - Core / Simulation: api/core/simulation.md
        - Core / Validation: api/core/validation.md
        - Legacy / Builder_Legacy: api/legacy/builder_legacy.md
        - Legacy / Main: api/legacy/main.md
        - Legacy / Plotter: api/legacy/plotter.md
        - Legacy / Simulator / Core: api/legacy/simulator/Core.md
        - Optimization / Water_Rocket_Optimizer: api/optimization/water_rocket_optimizer.md
        - Rocket / Builder: api/rocket/builder.md
        - Rocket / Geometry: api/rocket/geometry.md
        - Rocket / Materials: api/rocket/materials.md
        - Utils / Loader: api/utils/loader.md
        - Utils / Saver: api/utils/saver.md
        - Visualization / Flight_Animation: api/visualization/flight_animation.md
        - Visualization / Parameter_Explorer: api/visualization/parameter_explorer.md
        - Visualization / Parameter_Explorer_Debugging: api/visualization/parameter_explorer_debugging.md
        - Visualization / Plot_Flight_Data: api/visualization/plot_flight_data.md